desc: SD-1-4-Pre-train
network_kwargs:
    class_name: networks.sd1-4.SD1_4_Text_to_Image
    pre_train_model: /qiguojun/home/Models/CompVis/stable-diffusion-v1-4

data_loader_kwargs: 
    class_name: dataloaders.laion.load_laion_with_wds
    data_dir: /qiguojun/home/Dataset/laion_aes_recap_full
    batch_size: 4
    num_workers: 8

loss_kwargs: 
    class_name: losses.sd1-4.ImageLPIPSLoss
    text_loss_weight: 0.1
    P_mean: 0.0 
    P_std: 1.0
    sigma_data: 1.0
    p_uncond: 0.1
    dist: logitnormal

optimizer_kwargs:
    class_name: torch.optim.AdamW
    lr: 5.0e-4 # 5e-2/
    betas: [0.9, 0.99]
    eps: 1.0e-6

ema_kwargs:
    class_name: training.utils.ema.ModelEmaV2
    decay: 0.999

lr_scheduler_kwargs:
    class_name: training.utils.lr_scheduler.warmup_and_decay
    t_warmup: 10 # 10_000 kimg = 
    t_decay: 70000 # 7000 ？

# other training args
training_args:
    run_dir: /storage/litiancheng/timeprediction/ckpt/sd1-4
    total_steps: 1000_000
    grad_accumulation: 8
    # max_grad_norm: 1000 # default
    seed: 224
    step_per_tick: 15
    snapshot_ticks: 75
    state_dump_ticks: 75
    precision: bf16
    val_denoising_step: 32
    val_ticks: 10
    loss_scaling: 1
